apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cano-minimal
spec:
  profile: minimal
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
    pilot:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
