apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: handover-to-us
  namespace: emissary
spec:
  hostname: "*"
  precedence: 100
  prefix: /
  headers:
    x-region-target: us
  service: http://host.docker.internal:8080
  add_response_headers:
    x-routed-from:
      value: eu
    x-routed-to:
      value: us
  timeout_ms: 60000
  connect_timeout_ms: 6000
  idle_timeout_ms: 300000
  cluster_idle_timeout_ms: 300000
